### ISSUE TITLE
namespace polluting when launching from ipython console

### ISSUE THREAD

**Issue by EnricoGiampieri** [glue-viz/glue#1209]
Hi,

I'm trying to use glue interactively from a spyder IDE, and it works perfectly. I usually work from the spyder IPython console, and launch the glue interface interactively from there with something like:

    import pandas as pd
    from glue import qglue
    import pylab as plt
    df = pd.DataFrame(plt.randn(10, 3))
    app = qglue(xyz=df)

the app works and I can interact with it also from spyder, making the workflow really nice for mixing interactive exploration of data (in my case biological data) and proper scripting.
The only issue is that the namespace of app get mixed with the namespace of the original IPython console.

For example, after starting, `dc` becomes a global variable for my main script.
This could lead to some unexpected consequence, as it could overwrite some other variables I have previously created.

It imports apparently the whole pylab as `from pylab import *` and probably something else.
I detected around 990 new variables in the global namespace.

I would have expected these variables to be inside the object `app` instead, and as such would have a better encapsulation. I feel like exporting the variables to the global namespace should be an option to ease the interactivity, but not be the default behaviour when started in such case.

**Comment by astrofrog** [comment]
@EnricoGiampieri - thanks for the report. I think this should be solved in the developer version of glue. Could you try and let me know if that is the case?

**Comment by EnricoGiampieri** [comment]
Hi, I've just tried with the latest version, and the issue is gone if ipython is launched from terminal, but still present if I use the ipython console from spyder.
There seems to be some interaction between the 3 programs that leads to unexpected leaks...

I'm using:

    python 3.6.1
    glue version 0.11.1
    ipython 6.1.0
    spyder 3.2.2
    matplotlib 2.0.2

on a ubuntu linux (17.04)
