### ISSUE TITLE
Bug with point visibility in 3D scatter plots

### ISSUE THREAD

**Issue by ReubenCreighton** [glue-viz/glue#1478]
I'm getting a bug where if I change the 'fixed' colour for data points in the 3D scatter plots, all the points disappear. If I change to a gradient based on a variable, I can see the points again. This is not an issue of the points being too small, etc. They go from being visible in gradient mode to completely invisible in fixed mode.

**Comment by ReubenCreighton** [comment]
Hi, just to provide more info, all the data points are initially rendered as partly transparent squares. If you change the symbol in the 'plot layers' section, there is no change.  Gluevis (0.10.4) was installed using the Anaconda Navigator. 

![3dbug](https://user-images.githubusercontent.com/33887797/33112098-865b9e08-cfa5-11e7-9bb2-0dd3befc63e0.jpg)

**Comment by astrofrog** [comment]
@ReubenCreighton - I think this issue was fixed in a recent version of glue. If you are using the Anaconda navigator, you should make sure that you have added the 'glueviz' channel, as described here:

http://glueviz.org/en/stable/installation/conda.html#graphical-user-interface

The latest version should be 0.12.2 - can you let me know if you are able to update to that version?

**Comment by ReubenCreighton** [comment]
Hi, thanks for the reply. 
I tried this, unfortunately the problem is still occurring. 
![ver 12 update](https://user-images.githubusercontent.com/33887797/33190031-a58faadc-d0fc-11e7-8254-9738485cd245.jpg)

**Comment by astrofrog** [comment]
@ReubenCreighton - thanks for confirming this is still present. I don't have a Windows machine at the moment but I'll try and get my hands on one shortly to try and debug this.
